name: main

on:
  pull_request:
    branches:
    - master

jobs:
  main-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - env:
              TASK: lint
            allow_failures: false
            command: npm run lint

          - env:
              TASK: test
            allow_failures: false
            command: npm test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.10.0
      - name: ${{ matrix.env.TASK }}
        run: TASK=${{ matrix.env.TASK }} ${{ matrix.command }}
